# Path to your dotfiles relative to your $HOME directory
dotfiles_dir = "my_dotfiles"

[settings]
# Post install commands
posthooks = [ "sway reload" ]

# Vars hold  an array of paths to a toml file containing the variables to inject in your templatize dotfiles.
vars = [
    "bombadil/themes/default.toml",
    "bombadil/vars.toml",
    "bombadil/themes/palette.toml"
]

# A dot entry representing a symlink, `source` is relative to `dotfiles_dir`
# and target shall be relative to $HOME directory or absolute.
[settings.dots]
alacritty = { source = "alacritty", target = ".config/alacritty" }
sway = { source = "sway", target = ".config/sway" }
zsh = { source = "zsh/zshrc", target = ".zshrc" }
