# - A var file MUST contains valid toml.
# - The name of the file can be anything (ex: color-scheme.toml).
# - A bombadil config can have many var files.
[theme]
terminal = "alacritty"
background = "#292C3E"
foreground = "#EBEBEB"
text = "#FF261E"
cursor = "#FF261E"
black = "#0d0d0d"
red = "#FF301B"
green = "#A0E521"
yellow = "#FFC620"
blue = "#1BA6FA"